permalink: /blog/:year/:month/:title.html 
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
markdown: kramdown
highlights: pygments
url: https://github.com/xiangxiaoxiao/xiangxiaoxiao.github.io.git
lsi: false
safe: true
timezone: Asia/Wuhan
auto: false 

paginate: 8
paginate_path: "page:num"

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

JB :
  IMAGE_PATH : http://coolshell.info/images

# presonal config
domain: http://coolshell.info
title: 话唠先生
description: love live,love code,love life
author: Li Ming
email: 362471259@qq.com
github: xiangxiaoxiao

config:
  js_dir:
  img_dir:
  css_dir:
